#!/usr/bin/env bats
# devseed's onboarding clone: a personal config often lives in a PRIVATE
# GitHub repo, and onboarding runs before any prereq table exists, so the
# GitHub chain has to be reachable from here.

setup() {
  TMP="$(mktemp -d)"
  SHIM="$TMP/shim"
  mkdir -p "$SHIM"
  # deliberately NOT $PATH: the host's own /opt/homebrew/bin/gh would
  # otherwise satisfy `command -v gh` and hide what we are testing.
  export PATH="$SHIM:/usr/bin:/bin:/usr/sbin:/sbin"
  export HOME="$TMP/home"
  mkdir -p "$HOME"
  export DEVSEED_ROOT="$TMP/devseed"
  mkdir -p "$DEVSEED_ROOT"
  # keep every brew lookup inside the sandbox
  export DEVSEED_BREW_PREFIX="$TMP/brew"
  mkdir -p "$DEVSEED_BREW_PREFIX/bin"
  DEVSEED="$BATS_TEST_DIRNAME/../devseed"

  shim() { # name, body
    printf '#!/bin/bash\n%s\n' "$2" >"$SHIM/$1"
    chmod +x "$SHIM/$1"
  }

  shim curl 'exit 0'
  shim ssh 'echo "Permission denied (publickey)." >&2; exit 255'
  shim ssh-keygen "mkdir -p \"\$HOME/.ssh\"; touch \"\$HOME/.ssh/id_ed25519\" \"\$HOME/.ssh/id_ed25519.pub\""
  shim gh "echo \"gh \$*\" >>\"$TMP/gh.log\"; [ \"\$1\" = auth ] && [ \"\$2\" = status ] && exit 1; exit 0"
  shim hostname 'echo testmac'
}

teardown() { rm -rf "$TMP"; }

# `git clone` succeeds on the Nth call and fails before that.
git_fails_until() { # n
  cat >"$SHIM/git" <<EOF
#!/bin/bash
echo "git \$*" >>"$TMP/git.log"
n=\$(wc -l <"$TMP/git.log" | tr -d ' ')
if [ "\$n" -lt $1 ]; then
  echo "fatal: repository not found" >&2
  exit 128
fi
mkdir -p "\$3"
exit 0
EOF
  chmod +x "$SHIM/git"
  : >"$TMP/git.log"
}

load_devseed() { . "$DEVSEED" >/dev/null 2>&1 || true; }

@test "a public clone that works never touches GitHub setup" {
  git_fails_until 1
  load_devseed
  run clone_config https://github.com/someone/config.git
  [ "$status" -eq 0 ]
  [ ! -f "$TMP/gh.log" ]                  # gh never invoked
  [ ! -f "$HOME/.ssh/id_ed25519" ]        # no key generated
}

@test "a failed GitHub clone sets up access and retries once" {
  git_fails_until 2
  # already authenticated, so the chain goes straight to registering the
  # key; the interactive login branch is covered in test/preflight.bats
  shim gh "echo \"gh \$*\" >>\"$TMP/gh.log\"; exit 0"
  load_devseed
  run clone_config https://github.com/someone/private.git
  [ "$status" -eq 0 ]
  [[ "$output" == *"setting up GitHub access"* ]]
  [ -f "$HOME/.ssh/id_ed25519.pub" ]      # key generated by the chain
  grep -q "ssh-key add" "$TMP/gh.log"     # and registered
  [ "$(grep -c clone "$TMP/git.log")" -eq 2 ]
}

@test "a failed non-GitHub clone fails without touching GitHub" {
  git_fails_until 99
  load_devseed
  run clone_config https://gitlab.com/someone/config.git
  [ "$status" -ne 0 ]
  [[ "$output" == *"clone failed"* ]]
  [ ! -f "$TMP/gh.log" ]
  [ "$(grep -c clone "$TMP/git.log")" -eq 1 ]   # no retry
}

@test "a GitHub clone that still fails after setup reports it" {
  git_fails_until 99
  load_devseed
  run clone_config git@github.com:someone/private.git
  [ "$status" -ne 0 ]
  [[ "$output" == *"still failing after GitHub setup"* ]]
  [ "$(grep -c clone "$TMP/git.log")" -eq 2 ]   # tried once, retried once
}

@test "ensure_gh installs gh through brew when it is missing" {
  # remove the gh shim so ensure_gh has to install it
  rm -f "$SHIM/gh"
  cat >"$DEVSEED_BREW_PREFIX/bin/brew" <<EOF
#!/bin/bash
echo "brew \$*" >>"$TMP/brew.log"
[ "\$1" = install ] && printf '#!/bin/bash\nexit 0\n' >"$DEVSEED_BREW_PREFIX/bin/gh" && chmod +x "$DEVSEED_BREW_PREFIX/bin/gh"
exit 0
EOF
  chmod +x "$DEVSEED_BREW_PREFIX/bin/brew"
  load_devseed
  run ensure_gh
  [ "$status" -eq 0 ]
  grep -q "brew install gh" "$TMP/brew.log"
}
