#!/bin/bash
# defaults.sh — macOS defaults layer (key-level allowlist, Annex A.6).
# diff lands in M2, apply in M3.
# Scalar-only in v1: capture refuses array/dict/data (exit 2, naming the
# key); booleans normalized to true/false; absent keys recorded as <unset>
# (apply skips them).

apply_defaults() { die "apply_defaults: not implemented yet (M3)" 2; }

# diff_defaults — compare values.tsv against the machine, read-only.
# Drift kinds: differs / unset-on-machine / unset-in-config /
# non-scalar-on-machine (reported, never a hard death in diff).
diff_defaults() {
  local st=0 values domain key dtype want actual have
  values="$(config_dir)/defaults/values.tsv"
  if [ ! -f "$values" ]; then
    return 0
  fi
  while IFS="$(printf '\t')" read -r domain key dtype want; do
    [ -n "$domain" ] || continue
    if ! actual="$(defaults read-type "$domain" "$key" 2>/dev/null)"; then
      if [ "$want" != "<unset>" ]; then
        log "defaults: unset-on-machine: $domain $key (config=$want)"
        DEVSEED_N_DRIFT=$((DEVSEED_N_DRIFT + 1))
        st=1
      fi
      continue
    fi
    actual="${actual#Type is }"
    case "$actual" in
      array | dictionary | data)
        log "defaults: non-scalar-on-machine: $domain $key ($actual; remove from allowlist.tsv)"
        DEVSEED_N_DRIFT=$((DEVSEED_N_DRIFT + 1))
        st=1
        continue
        ;;
    esac
    have="$(defaults read "$domain" "$key")"
    if [ "$dtype" = "bool" ] || [ "$actual" = "boolean" ]; then
      have="$(defaults_normalize_bool "$have")"
    fi
    if [ "$want" = "<unset>" ]; then
      log "defaults: unset-in-config: $domain $key (machine=$have)"
      DEVSEED_N_DRIFT=$((DEVSEED_N_DRIFT + 1))
      st=1
    elif [ "$have" != "$want" ]; then
      log "defaults: differs: $domain $key (config=$want machine=$have)"
      DEVSEED_N_DRIFT=$((DEVSEED_N_DRIFT + 1))
      st=1
    fi
  done <<EOF
$(tsv_rows "$values")
EOF
  return "$st"
}

# defaults_normalize_bool VALUE — canonical true/false.
defaults_normalize_bool() {
  case "$1" in
    1 | true | TRUE | YES | yes) echo "true" ;;
    0 | false | FALSE | NO | no) echo "false" ;;
    *) echo "$1" ;;
  esac
}

# capture_defaults — read every allowlisted key and rewrite values.tsv
# (sorted, deterministic).
capture_defaults() {
  local allow rows_tmp values_tmp domain key dtype actual value
  allow="$(config_dir)/defaults/allowlist.tsv"
  if [ ! -f "$allow" ]; then
    log "defaults: no allowlist.tsv; skipping"
    return 0
  fi
  rows_tmp="$(mktemp)"
  values_tmp="$(mktemp)"

  while IFS="$(printf '\t')" read -r domain key dtype; do
    [ -n "$domain" ] || continue
    if ! actual="$(defaults read-type "$domain" "$key" 2>/dev/null)"; then
      printf '%s\t%s\t%s\t%s\n' "$domain" "$key" "$dtype" "<unset>" >>"$rows_tmp"
      continue
    fi
    actual="${actual#Type is }"
    case "$actual" in
      array | dictionary | data)
        die "defaults: $domain $key has non-scalar type '$actual' (v1 is scalar-only; remove it from allowlist.tsv)" 2
        ;;
    esac
    value="$(defaults read "$domain" "$key")"
    if [ "$dtype" = "bool" ] || [ "$actual" = "boolean" ]; then
      value="$(defaults_normalize_bool "$value")"
    fi
    printf '%s\t%s\t%s\t%s\n' "$domain" "$key" "$dtype" "$value" >>"$rows_tmp"
  done <<EOF
$(tsv_rows "$allow")
EOF

  {
    printf '# values.tsv — captured desired values for allowlisted defaults keys.\n'
    printf '# domain<TAB>key<TAB>type<TAB>value; <unset> = key absent (apply skips).\n'
    printf '# Generated by devseed capture; kept sorted for minimal diffs.\n'
    LC_ALL=C sort "$rows_tmp"
  } >"$values_tmp"
  run_cmd cp "$values_tmp" "$(config_dir)/defaults/values.tsv"
  rm -f "$rows_tmp" "$values_tmp"
  log "defaults: captured $(tsv_rows "$allow" | grep -c . || true) allowlisted keys"
  return 0
}
