#!/bin/bash
# defaults.sh — macOS defaults layer (key-level allowlist, Annex A.6).
# diff lands in M2, apply in M3.
# Scalar-only in v1: capture refuses array/dict/data (exit 2, naming the
# key); booleans normalized to true/false; absent keys recorded as <unset>
# (apply skips them).

diff_defaults() { die "diff_defaults: not implemented yet (M2)" 2; }
apply_defaults() { die "apply_defaults: not implemented yet (M3)" 2; }

# defaults_normalize_bool VALUE — canonical true/false.
defaults_normalize_bool() {
  case "$1" in
    1 | true | TRUE | YES | yes) echo "true" ;;
    0 | false | FALSE | NO | no) echo "false" ;;
    *) echo "$1" ;;
  esac
}

# capture_defaults — read every allowlisted key and rewrite values.tsv
# (sorted, deterministic).
capture_defaults() {
  local allow rows_tmp values_tmp domain key dtype actual value
  allow="$(config_dir)/defaults/allowlist.tsv"
  if [ ! -f "$allow" ]; then
    log "defaults: no allowlist.tsv; skipping"
    return 0
  fi
  rows_tmp="$(mktemp)"
  values_tmp="$(mktemp)"

  while IFS="$(printf '\t')" read -r domain key dtype; do
    [ -n "$domain" ] || continue
    if ! actual="$(defaults read-type "$domain" "$key" 2>/dev/null)"; then
      printf '%s\t%s\t%s\t%s\n' "$domain" "$key" "$dtype" "<unset>" >>"$rows_tmp"
      continue
    fi
    actual="${actual#Type is }"
    case "$actual" in
      array | dictionary | data)
        die "defaults: $domain $key has non-scalar type '$actual' (v1 is scalar-only; remove it from allowlist.tsv)" 2
        ;;
    esac
    value="$(defaults read "$domain" "$key")"
    if [ "$dtype" = "bool" ] || [ "$actual" = "boolean" ]; then
      value="$(defaults_normalize_bool "$value")"
    fi
    printf '%s\t%s\t%s\t%s\n' "$domain" "$key" "$dtype" "$value" >>"$rows_tmp"
  done <<EOF
$(tsv_rows "$allow")
EOF

  {
    printf '# values.tsv — captured desired values for allowlisted defaults keys.\n'
    printf '# domain<TAB>key<TAB>type<TAB>value; <unset> = key absent (apply skips).\n'
    printf '# Generated by devseed capture; kept sorted for minimal diffs.\n'
    LC_ALL=C sort "$rows_tmp"
  } >"$values_tmp"
  run_cmd cp "$values_tmp" "$(config_dir)/defaults/values.tsv"
  rm -f "$rows_tmp" "$values_tmp"
  log "defaults: captured $(tsv_rows "$allow" | grep -c . || true) allowlisted keys"
  return 0
}
